/****************************
 * 
 * Generated by Deepseek.
 * It seems that it works farely well.
 * I will maybe rewrite this after I learn physics.:)
 * I added a function myself.
 * 
 * **************************/

#pragma once

#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/gtx/quaternion.hpp>  // 用于 angleAxis
#include <array>
#include <vector>
#include <cmath>
#include <algorithm>

class Cube {
public:
	// 物理状态
	glm::vec3 position;		   // 质心位置
	glm::quat orientation;		// 旋转（局部→世界）
	glm::vec3 linear_velocity;	// 线速度
	glm::vec3 angular_velocity;   // 角速度

	// 物理参数
	float mass;				   // 质量
	float inertia;				// 转动惯量（标量，立方体三轴相等）
	float restitution;			// 法向恢复系数 (0~1)
	float friction;			   // 动摩擦系数

	// 常量
	static constexpr float GRAVITY = 20.0f;		// 重力加速度 m/s^2
	static constexpr float CONTACT_THRESHOLD = 1e-4f; // 接触判定阈值

	// 构造函数，默认质量=1，恢复系数=0.5，摩擦系数=0.5
	Cube(const glm::vec3& pos = glm::vec3(0.0f),
		const glm::quat& orient = glm::quat(1.0f, 0.0f, 0.0f, 0.0f),
		const glm::vec3& lin_vel = glm::vec3(0.0f),
		const glm::vec3& ang_vel = glm::vec3(0.0f),
		float e = 0.5f,
		float mu = 0.5f) :
		position(pos), orientation(orient), linear_velocity(lin_vel),
		angular_velocity(ang_vel), mass(1.0f), restitution(e), friction(mu) {
		// 立方体棱长2，关于质心的转动惯量 I = (1/6)*M*(a^2) ，a=2 => I = (2/3)*M
		inertia = (2.0f / 3.0f) * mass;
	}

	// 更新一帧，时间步长 dt (秒)
	void update(float dt) {
		// 1. 重力加速度影响线速度
		linear_velocity += glm::vec3(0.0f, -GRAVITY, 0.0f) * dt;

		// 2. 预测位置
		position += linear_velocity * dt;

		// 3. 根据角速度更新旋转（使用增量旋转）
		float ang_speed = glm::length(angular_velocity);
		if (ang_speed > 1e-6f) {
			float angle = ang_speed * dt;
			glm::vec3 axis = angular_velocity / ang_speed;
			glm::quat delta_q = glm::angleAxis(angle, axis);   // 世界坐标系下的增量旋转
			orientation = delta_q * orientation;			   // 左乘：先应用增量，再应用原旋转
			orientation = glm::normalize(orientation);
		}

		// 4. 碰撞检测与响应
		auto vertices = computeVertices();   // 当前预测位置下的顶点坐标

		// 4.1 找出最大穿透深度
		float max_penetration = 0.0f;
		for (const auto& v : vertices) {
			if (v.y < 0.0f) {
				max_penetration = std::max(max_penetration, -v.y);
			}
		}

		if (max_penetration > 0.0f) {
			// 4.2 位置修正：将立方体向上移动最大穿透深度，使最深点刚好接触地面
			position.y += max_penetration;

			// 4.3 重新计算顶点（现在所有点 y >= 0）
			vertices = computeVertices();

			// 4.4 迭代求解速度冲量（顺序冲量法，迭代4次）
			const int iterations = 4;
			for (int iter = 0; iter < iterations; ++iter) {
				// 收集当前接触点（y 接近0）
				std::vector<glm::vec3> contacts;
				for (const auto& v : vertices) {
					if (v.y <= CONTACT_THRESHOLD) {
						contacts.push_back(v);
					}
				}

				for (const auto& P : contacts) {
					glm::vec3 r = P - position;			   // 接触点相对质心的向量
					glm::vec3 v_rel = linear_velocity + glm::cross(angular_velocity, r);
					glm::vec3 n(0.0f, 1.0f, 0.0f);			// 地面法向

					float v_rel_n = glm::dot(v_rel, n);
					if (v_rel_n < -1e-6f) {					// 正在接近地面
						// --- 法向冲量 ---
						float r_dot_n = glm::dot(r, n);
						float r_perp_sq = glm::dot(r, r) - r_dot_n * r_dot_n; // |r|² - (r·n)²
						float eff_mass_n_inv = 1.0f / mass + r_perp_sq / inertia;
						float J_n = -(1.0f + restitution) * v_rel_n / eff_mass_n_inv;

						// 应用法向冲量
						linear_velocity += (J_n * n) / mass;
						angular_velocity += glm::cross(r, J_n * n) / inertia;

						// 更新相对速度（用于后续切向计算）
						v_rel = linear_velocity + glm::cross(angular_velocity, r);

						// --- 切向冲量（库仑摩擦）---
						glm::vec3 v_rel_t = v_rel - glm::dot(v_rel, n) * n;
						float v_rel_t_len = glm::length(v_rel_t);
						if (v_rel_t_len > 1e-6f) {
							glm::vec3 t = -glm::normalize(v_rel_t);   // 冲量方向与滑动方向相反
							float r_dot_t = glm::dot(r, t);
							float r_perp_t_sq = glm::dot(r, r) - r_dot_t * r_dot_t; // |r|² - (r·t)²
							float eff_mass_t_inv = 1.0f / mass + r_perp_t_sq / inertia;

							// 使切向速度归零所需的冲量大小
							float J_t_desired = v_rel_t_len / eff_mass_t_inv;
							float J_t_max = friction * J_n;			// 库仑摩擦限制
							float J_t_mag = std::min(J_t_desired, J_t_max);

							glm::vec3 J_t_vec = J_t_mag * t;
							linear_velocity += J_t_vec / mass;
							angular_velocity += glm::cross(r, J_t_vec) / inertia;
						}
					}
				}
			}
		}
	}

	// 返回八个顶点的世界坐标（棱长为2，中心在质心）
	std::array<glm::vec3, 8> getVertices() const {
		return computeVertices();
	}

	glm::mat4 getTransformMatrix() const {
		return glm::translate(glm::mat4(1.0f), position) * glm::mat4_cast(orientation);
	}

	bool still() const {
		return fabs(linear_velocity.x) < 1e-1f &&
			fabs(linear_velocity.y) < 1e-1f &&
			fabs(linear_velocity.z) < 1e-1f;
	}

    // 返回当前世界坐标系中朝上的面的编号
    // 编号定义：3-上(0,1,0), 2-下(0,-1,0), 5-前(0,0,1), 0-后(0,0,-1), 1-右(1,0,0), 4-左(-1,0,0)
    int getTopFace() const {
        // 局部法线：上、下、前、后、右、左
        std::array<glm::vec3, 6> local_normals = {
            glm::vec3(0, 0, -1),  // 0: back
            glm::vec3(1, 0, 0),   // 1: right
            glm::vec3(0, -1, 0),  // 2: down
            glm::vec3(0, 1, 0),   // 3: up
            glm::vec3(-1, 0, 0),  // 4: left
            glm::vec3(0, 0, 1)    // 5: front
        };
        float max_dot = -1.0f;
        int best = 0;
        glm::vec3 world_up(0, 1, 0);
        for (int i = 0; i < 6; ++i) {
            glm::vec3 world_normal = orientation * local_normals[i];
            float dot = glm::dot(world_normal, world_up);
            if (dot > max_dot) {
                max_dot = dot;
                best = i;
            }
        }
        return best;
    }
private:
	// 根据当前 position 和 orientation 计算八个顶点
	std::array<glm::vec3, 8> computeVertices() const {
		std::array<glm::vec3, 8> vertices;
		int idx = 0;
		for (int ix = -1; ix <= 1; ix += 2) {
			for (int iy = -1; iy <= 1; iy += 2) {
				for (int iz = -1; iz <= 1; iz += 2) {
					glm::vec3 local(ix, iy, iz);		  // 局部坐标 (±1, ±1, ±1)
					vertices[idx++] = position + orientation * local;
				}
			}
		}
		return vertices;
	}
};